### PR TITLE
Fix Haml template generation

### PR DESCRIPTION
**Pull request by jayshepherd**
## What is the purpose of this pull request?
The Haml option was not using the correct name or Haml template content.

## What changes did you make? (overview)
1. Renamed the filename to '...html.haml.tt'
2. Updated the template content to be Haml compatible

## Checklist

- [ ] I've added tests for this change
- [ ] I've added a Changelog entry
- [ ] I've updated a documentation

### CODE REVIEW

**Comment by palkan** [comment]
Thanks!

**Comment by brodienguyen** [comment]
@palkan Hi there. Just want to confirm if this change is going to be included in the upcoming release. I have check the current script hasn't been updated so the HAML template is still broken

**Comment by palkan** [comment]
> I have check the current script hasn't been updated

You mean RailsBytes script? I've just published the new one; the change is there.

**Comment by brodienguyen** [comment]
> > I have check the current script hasn't been updated
> 
> You mean RailsBytes script? I've just published the new one; the change is there.

Yes I meant the RailsBytes script. Sorry I did make it clear before. Thanks heaps for your time to contribute in this project and make the view_component neater.

**Pull request merged**
